# Generated by Django 4.1.1 on 2024-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_done_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
